# Generated by Django 3.2.7 on 2021-10-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='women',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
